# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import numpy
import numpy.typing
import typing
__all__ = [
    "Model",
]

@typing.final
class Model:
    @property
    def frequency(self) -> numpy.typing.NDArray[numpy.float64]: ...
    def __new__(cls, path: builtins.str, args: typing.Sequence[builtins.str]) -> Model: ...
    def compute(self) -> None: ...
    def __getattr__(self, name: builtins.str) -> numpy.typing.NDArray[numpy.float64]: ...

