# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import numpy
import numpy.typing
import os
import pathlib
import typing

__all__ = [
    "AmError",
    "ComputeError",
    "ConfigError",
    "Model",
]

class AmError(builtins.Exception):
    r"""
    Base exception for am errors.
    """

    ...

class ComputeError(builtins.AmError):
    r"""
    Error during model computation.
    """

    ...

class ConfigError(builtins.AmError):
    r"""
    Error parsing an .amc configuration file.
    """

    ...

@typing.final
class Model:
    r"""
    An am atmospheric model loaded from an ``.amc`` configuration file.

    Parameters
    ----------
    path:
        Path to the ``.amc`` file.
    args:
        Positional substitution values for ``%1``, ``%2``, … placeholders
        in the config (frequency grid, zenith angle, PWV scale, etc.).

    Examples
    --------
    .. code-block:: python

        m = am.Model("SPole_JJA_75.amc", [0, "GHz", 350, "GHz", 0.5, "GHz", 35, "deg", 1.0])
        m.compute()
        m.outputs["tb_rj"]
    """
    @property
    def frequency(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Frequency grid in GHz.
        """
    @property
    def raw_outputs(
        self,
    ) -> builtins.dict[builtins.str, numpy.typing.NDArray[numpy.float64]]:
        r"""
        Dict mapping output name to computed spectrum array.

        Use the Python ``Model`` wrapper for xarray outputs.
        """
    @property
    def variables(self) -> builtins.list[builtins.str]:
        r"""
        Names of fit/differentiation variables defined in the ``.amc`` config.
        """
    @property
    def n_variables(self) -> builtins.int:
        r"""
        Number of fit/differentiation variables.
        """
    def __new__(
        cls,
        path: builtins.str | os.PathLike | pathlib.Path,
        args: typing.Sequence[typing.Any],
    ) -> Model: ...
    def compute(self) -> None:
        r"""
        Run the radiative transfer computation.

        Releases the GIL while running so other Python threads are not blocked.
        Must be called before accessing :attr:`outputs`.
        """
    def raw_jacobian(
        self,
    ) -> builtins.dict[builtins.str, numpy.typing.NDArray[numpy.float64]]:
        r"""
        Compute Jacobians of all outputs wrt fit variables.

        Use the Python ``Model`` wrapper for xarray outputs.
        """
    def summary(self) -> builtins.str:
        r"""
        Full resolved model configuration, as am would print it to stderr.

        Equivalent to running ``am`` on the command line with the same arguments.
        Also available as ``str(model)`` / ``print(model)``.
        """
    def __str__(self) -> builtins.str: ...
