/* automatically generated by rust-bindgen 0.72.1 */

pub type FILE = std::os::raw::c_void;

pub type __uint64_t = ::std::os::raw::c_ulong;
pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
pub type _IO_lock_t = ::std::os::raw::c_void;
unsafe extern "C" {
    pub static MODEL_INIT: model_t;
}
unsafe extern "C" {
    pub static SIMPLEX_INIT: simplex_t;
}
unsafe extern "C" {
    pub static FIT_DATA_INIT: fit_data_t;
}
pub type gridsize_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct gridrange_t {
    pub min: gridsize_t,
    pub max: gridsize_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of gridrange_t"][::std::mem::size_of::<gridrange_t>() - 8usize];
    ["Alignment of gridrange_t"][::std::mem::align_of::<gridrange_t>() - 4usize];
    ["Offset of field: gridrange_t::min"][::std::mem::offset_of!(gridrange_t, min) - 0usize];
    ["Offset of field: gridrange_t::max"][::std::mem::offset_of!(gridrange_t, max) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct model_t {
    pub fmin: f64,
    pub fmax: f64,
    pub df: f64,
    pub fout_min: f64,
    pub fout_max: f64,
    pub flo: f64,
    pub fif_0: f64,
    pub fif_delta: f64,
    pub fif_min: f64,
    pub fif_max: f64,
    pub ils_fwhm: f64,
    pub ils_fif: f64,
    pub dsb_utol_ratio: f64,
    pub rx_gain_factor: f64,
    pub RH_offset_exp: f64,
    pub RH_scale: f64,
    pub g: f64,
    pub dg_dz: f64,
    pub R0: f64,
    pub z0: f64,
    pub p: f64,
    pub Ptoa: f64,
    pub Pmax: f64,
    pub Pobs: f64,
    pub zobs: f64,
    pub Psource: f64,
    pub zsource: f64,
    pub Ptan: f64,
    pub ztan: f64,
    pub tol: f64,
    pub selfbroad_vmr_tol: f64,
    pub T0: f64,
    pub Trx: f64,
    pub Tref: f64,
    pub kcache_Tmin: f64,
    pub kcache_Tmax: f64,
    pub kcache_dT: f64,
    pub sec_za: f64,
    pub za: f64,
    pub am_runtime: f64,
    pub od_runtime: f64,
    pub rt_runtime: f64,
    pub spec_runtime: f64,
    pub runtime: f64,
    pub f: *mut f64,
    pub f2: *mut f64,
    pub fif: *mut f64,
    pub ils: *mut f64,
    pub ilsworkspace: *mut f64,
    pub tau: *mut f64,
    pub tx: *mut f64,
    pub I0: *mut f64,
    pub I: *mut f64,
    pub I_ref: *mut f64,
    pub I_diff: *mut f64,
    pub Tb: *mut f64,
    pub Trj: *mut f64,
    pub Tsys: *mut f64,
    pub Y: *mut f64,
    pub L: *mut f64,
    pub tau_fsl: *mut f64,
    pub k_out: *mut f64,
    pub layer: *mut *mut layer_t,
    pub ngrid: gridsize_t,
    pub nif: gridsize_t,
    pub npad: gridsize_t,
    pub nLpad: gridsize_t,
    pub ilsb: gridrange_t,
    pub iusb: gridrange_t,
    pub isub: [gridrange_t; 2usize],
    pub nlayers: ::std::os::raw::c_int,
    pub path_begin: ::std::os::raw::c_int,
    pub path_mid: ::std::os::raw::c_int,
    pub path_end: ::std::os::raw::c_int,
    pub path_min: ::std::os::raw::c_int,
    pub nkcache: ::std::os::raw::c_int,
    pub fmin_unitnum: ::std::os::raw::c_int,
    pub fmax_unitnum: ::std::os::raw::c_int,
    pub df_unitnum: ::std::os::raw::c_int,
    pub fout_min_unitnum: ::std::os::raw::c_int,
    pub fout_max_unitnum: ::std::os::raw::c_int,
    pub flo_unitnum: ::std::os::raw::c_int,
    pub fif_min_unitnum: ::std::os::raw::c_int,
    pub fif_max_unitnum: ::std::os::raw::c_int,
    pub g_unitnum: ::std::os::raw::c_int,
    pub dg_dz_unitnum: ::std::os::raw::c_int,
    pub R0_unitnum: ::std::os::raw::c_int,
    pub z0_unitnum: ::std::os::raw::c_int,
    pub Pobs_unitnum: ::std::os::raw::c_int,
    pub zobs_unitnum: ::std::os::raw::c_int,
    pub Psource_unitnum: ::std::os::raw::c_int,
    pub zsource_unitnum: ::std::os::raw::c_int,
    pub Ptan_unitnum: ::std::os::raw::c_int,
    pub ztan_unitnum: ::std::os::raw::c_int,
    pub geometry: ::std::os::raw::c_int,
    pub ifmode: ::std::os::raw::c_int,
    pub ils_fwhm_unitnum: ::std::os::raw::c_int,
    pub ils_fif_unitnum: ::std::os::raw::c_int,
    pub ilsmode: ::std::os::raw::c_int,
    pub ils_typenum: ::std::os::raw::c_int,
    pub RH_adj_flag: ::std::os::raw::c_int,
    pub T0_unitnum: ::std::os::raw::c_int,
    pub Tref_unitnum: ::std::os::raw::c_int,
    pub Trx_unitnum: ::std::os::raw::c_int,
    pub PTmode: ::std::os::raw::c_int,
    pub za_unitnum: ::std::os::raw::c_int,
    pub log_runtimes: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of model_t"][::std::mem::size_of::<model_t>() - 704usize];
    ["Alignment of model_t"][::std::mem::align_of::<model_t>() - 8usize];
    ["Offset of field: model_t::fmin"][::std::mem::offset_of!(model_t, fmin) - 0usize];
    ["Offset of field: model_t::fmax"][::std::mem::offset_of!(model_t, fmax) - 8usize];
    ["Offset of field: model_t::df"][::std::mem::offset_of!(model_t, df) - 16usize];
    ["Offset of field: model_t::fout_min"][::std::mem::offset_of!(model_t, fout_min) - 24usize];
    ["Offset of field: model_t::fout_max"][::std::mem::offset_of!(model_t, fout_max) - 32usize];
    ["Offset of field: model_t::flo"][::std::mem::offset_of!(model_t, flo) - 40usize];
    ["Offset of field: model_t::fif_0"][::std::mem::offset_of!(model_t, fif_0) - 48usize];
    ["Offset of field: model_t::fif_delta"][::std::mem::offset_of!(model_t, fif_delta) - 56usize];
    ["Offset of field: model_t::fif_min"][::std::mem::offset_of!(model_t, fif_min) - 64usize];
    ["Offset of field: model_t::fif_max"][::std::mem::offset_of!(model_t, fif_max) - 72usize];
    ["Offset of field: model_t::ils_fwhm"][::std::mem::offset_of!(model_t, ils_fwhm) - 80usize];
    ["Offset of field: model_t::ils_fif"][::std::mem::offset_of!(model_t, ils_fif) - 88usize];
    ["Offset of field: model_t::dsb_utol_ratio"]
        [::std::mem::offset_of!(model_t, dsb_utol_ratio) - 96usize];
    ["Offset of field: model_t::rx_gain_factor"]
        [::std::mem::offset_of!(model_t, rx_gain_factor) - 104usize];
    ["Offset of field: model_t::RH_offset_exp"]
        [::std::mem::offset_of!(model_t, RH_offset_exp) - 112usize];
    ["Offset of field: model_t::RH_scale"][::std::mem::offset_of!(model_t, RH_scale) - 120usize];
    ["Offset of field: model_t::g"][::std::mem::offset_of!(model_t, g) - 128usize];
    ["Offset of field: model_t::dg_dz"][::std::mem::offset_of!(model_t, dg_dz) - 136usize];
    ["Offset of field: model_t::R0"][::std::mem::offset_of!(model_t, R0) - 144usize];
    ["Offset of field: model_t::z0"][::std::mem::offset_of!(model_t, z0) - 152usize];
    ["Offset of field: model_t::p"][::std::mem::offset_of!(model_t, p) - 160usize];
    ["Offset of field: model_t::Ptoa"][::std::mem::offset_of!(model_t, Ptoa) - 168usize];
    ["Offset of field: model_t::Pmax"][::std::mem::offset_of!(model_t, Pmax) - 176usize];
    ["Offset of field: model_t::Pobs"][::std::mem::offset_of!(model_t, Pobs) - 184usize];
    ["Offset of field: model_t::zobs"][::std::mem::offset_of!(model_t, zobs) - 192usize];
    ["Offset of field: model_t::Psource"][::std::mem::offset_of!(model_t, Psource) - 200usize];
    ["Offset of field: model_t::zsource"][::std::mem::offset_of!(model_t, zsource) - 208usize];
    ["Offset of field: model_t::Ptan"][::std::mem::offset_of!(model_t, Ptan) - 216usize];
    ["Offset of field: model_t::ztan"][::std::mem::offset_of!(model_t, ztan) - 224usize];
    ["Offset of field: model_t::tol"][::std::mem::offset_of!(model_t, tol) - 232usize];
    ["Offset of field: model_t::selfbroad_vmr_tol"]
        [::std::mem::offset_of!(model_t, selfbroad_vmr_tol) - 240usize];
    ["Offset of field: model_t::T0"][::std::mem::offset_of!(model_t, T0) - 248usize];
    ["Offset of field: model_t::Trx"][::std::mem::offset_of!(model_t, Trx) - 256usize];
    ["Offset of field: model_t::Tref"][::std::mem::offset_of!(model_t, Tref) - 264usize];
    ["Offset of field: model_t::kcache_Tmin"]
        [::std::mem::offset_of!(model_t, kcache_Tmin) - 272usize];
    ["Offset of field: model_t::kcache_Tmax"]
        [::std::mem::offset_of!(model_t, kcache_Tmax) - 280usize];
    ["Offset of field: model_t::kcache_dT"][::std::mem::offset_of!(model_t, kcache_dT) - 288usize];
    ["Offset of field: model_t::sec_za"][::std::mem::offset_of!(model_t, sec_za) - 296usize];
    ["Offset of field: model_t::za"][::std::mem::offset_of!(model_t, za) - 304usize];
    ["Offset of field: model_t::am_runtime"]
        [::std::mem::offset_of!(model_t, am_runtime) - 312usize];
    ["Offset of field: model_t::od_runtime"]
        [::std::mem::offset_of!(model_t, od_runtime) - 320usize];
    ["Offset of field: model_t::rt_runtime"]
        [::std::mem::offset_of!(model_t, rt_runtime) - 328usize];
    ["Offset of field: model_t::spec_runtime"]
        [::std::mem::offset_of!(model_t, spec_runtime) - 336usize];
    ["Offset of field: model_t::runtime"][::std::mem::offset_of!(model_t, runtime) - 344usize];
    ["Offset of field: model_t::f"][::std::mem::offset_of!(model_t, f) - 352usize];
    ["Offset of field: model_t::f2"][::std::mem::offset_of!(model_t, f2) - 360usize];
    ["Offset of field: model_t::fif"][::std::mem::offset_of!(model_t, fif) - 368usize];
    ["Offset of field: model_t::ils"][::std::mem::offset_of!(model_t, ils) - 376usize];
    ["Offset of field: model_t::ilsworkspace"]
        [::std::mem::offset_of!(model_t, ilsworkspace) - 384usize];
    ["Offset of field: model_t::tau"][::std::mem::offset_of!(model_t, tau) - 392usize];
    ["Offset of field: model_t::tx"][::std::mem::offset_of!(model_t, tx) - 400usize];
    ["Offset of field: model_t::I0"][::std::mem::offset_of!(model_t, I0) - 408usize];
    ["Offset of field: model_t::I"][::std::mem::offset_of!(model_t, I) - 416usize];
    ["Offset of field: model_t::I_ref"][::std::mem::offset_of!(model_t, I_ref) - 424usize];
    ["Offset of field: model_t::I_diff"][::std::mem::offset_of!(model_t, I_diff) - 432usize];
    ["Offset of field: model_t::Tb"][::std::mem::offset_of!(model_t, Tb) - 440usize];
    ["Offset of field: model_t::Trj"][::std::mem::offset_of!(model_t, Trj) - 448usize];
    ["Offset of field: model_t::Tsys"][::std::mem::offset_of!(model_t, Tsys) - 456usize];
    ["Offset of field: model_t::Y"][::std::mem::offset_of!(model_t, Y) - 464usize];
    ["Offset of field: model_t::L"][::std::mem::offset_of!(model_t, L) - 472usize];
    ["Offset of field: model_t::tau_fsl"][::std::mem::offset_of!(model_t, tau_fsl) - 480usize];
    ["Offset of field: model_t::k_out"][::std::mem::offset_of!(model_t, k_out) - 488usize];
    ["Offset of field: model_t::layer"][::std::mem::offset_of!(model_t, layer) - 496usize];
    ["Offset of field: model_t::ngrid"][::std::mem::offset_of!(model_t, ngrid) - 504usize];
    ["Offset of field: model_t::nif"][::std::mem::offset_of!(model_t, nif) - 508usize];
    ["Offset of field: model_t::npad"][::std::mem::offset_of!(model_t, npad) - 512usize];
    ["Offset of field: model_t::nLpad"][::std::mem::offset_of!(model_t, nLpad) - 516usize];
    ["Offset of field: model_t::ilsb"][::std::mem::offset_of!(model_t, ilsb) - 520usize];
    ["Offset of field: model_t::iusb"][::std::mem::offset_of!(model_t, iusb) - 528usize];
    ["Offset of field: model_t::isub"][::std::mem::offset_of!(model_t, isub) - 536usize];
    ["Offset of field: model_t::nlayers"][::std::mem::offset_of!(model_t, nlayers) - 552usize];
    ["Offset of field: model_t::path_begin"]
        [::std::mem::offset_of!(model_t, path_begin) - 556usize];
    ["Offset of field: model_t::path_mid"][::std::mem::offset_of!(model_t, path_mid) - 560usize];
    ["Offset of field: model_t::path_end"][::std::mem::offset_of!(model_t, path_end) - 564usize];
    ["Offset of field: model_t::path_min"][::std::mem::offset_of!(model_t, path_min) - 568usize];
    ["Offset of field: model_t::nkcache"][::std::mem::offset_of!(model_t, nkcache) - 572usize];
    ["Offset of field: model_t::fmin_unitnum"]
        [::std::mem::offset_of!(model_t, fmin_unitnum) - 576usize];
    ["Offset of field: model_t::fmax_unitnum"]
        [::std::mem::offset_of!(model_t, fmax_unitnum) - 580usize];
    ["Offset of field: model_t::df_unitnum"]
        [::std::mem::offset_of!(model_t, df_unitnum) - 584usize];
    ["Offset of field: model_t::fout_min_unitnum"]
        [::std::mem::offset_of!(model_t, fout_min_unitnum) - 588usize];
    ["Offset of field: model_t::fout_max_unitnum"]
        [::std::mem::offset_of!(model_t, fout_max_unitnum) - 592usize];
    ["Offset of field: model_t::flo_unitnum"]
        [::std::mem::offset_of!(model_t, flo_unitnum) - 596usize];
    ["Offset of field: model_t::fif_min_unitnum"]
        [::std::mem::offset_of!(model_t, fif_min_unitnum) - 600usize];
    ["Offset of field: model_t::fif_max_unitnum"]
        [::std::mem::offset_of!(model_t, fif_max_unitnum) - 604usize];
    ["Offset of field: model_t::g_unitnum"][::std::mem::offset_of!(model_t, g_unitnum) - 608usize];
    ["Offset of field: model_t::dg_dz_unitnum"]
        [::std::mem::offset_of!(model_t, dg_dz_unitnum) - 612usize];
    ["Offset of field: model_t::R0_unitnum"]
        [::std::mem::offset_of!(model_t, R0_unitnum) - 616usize];
    ["Offset of field: model_t::z0_unitnum"]
        [::std::mem::offset_of!(model_t, z0_unitnum) - 620usize];
    ["Offset of field: model_t::Pobs_unitnum"]
        [::std::mem::offset_of!(model_t, Pobs_unitnum) - 624usize];
    ["Offset of field: model_t::zobs_unitnum"]
        [::std::mem::offset_of!(model_t, zobs_unitnum) - 628usize];
    ["Offset of field: model_t::Psource_unitnum"]
        [::std::mem::offset_of!(model_t, Psource_unitnum) - 632usize];
    ["Offset of field: model_t::zsource_unitnum"]
        [::std::mem::offset_of!(model_t, zsource_unitnum) - 636usize];
    ["Offset of field: model_t::Ptan_unitnum"]
        [::std::mem::offset_of!(model_t, Ptan_unitnum) - 640usize];
    ["Offset of field: model_t::ztan_unitnum"]
        [::std::mem::offset_of!(model_t, ztan_unitnum) - 644usize];
    ["Offset of field: model_t::geometry"][::std::mem::offset_of!(model_t, geometry) - 648usize];
    ["Offset of field: model_t::ifmode"][::std::mem::offset_of!(model_t, ifmode) - 652usize];
    ["Offset of field: model_t::ils_fwhm_unitnum"]
        [::std::mem::offset_of!(model_t, ils_fwhm_unitnum) - 656usize];
    ["Offset of field: model_t::ils_fif_unitnum"]
        [::std::mem::offset_of!(model_t, ils_fif_unitnum) - 660usize];
    ["Offset of field: model_t::ilsmode"][::std::mem::offset_of!(model_t, ilsmode) - 664usize];
    ["Offset of field: model_t::ils_typenum"]
        [::std::mem::offset_of!(model_t, ils_typenum) - 668usize];
    ["Offset of field: model_t::RH_adj_flag"]
        [::std::mem::offset_of!(model_t, RH_adj_flag) - 672usize];
    ["Offset of field: model_t::T0_unitnum"]
        [::std::mem::offset_of!(model_t, T0_unitnum) - 676usize];
    ["Offset of field: model_t::Tref_unitnum"]
        [::std::mem::offset_of!(model_t, Tref_unitnum) - 680usize];
    ["Offset of field: model_t::Trx_unitnum"]
        [::std::mem::offset_of!(model_t, Trx_unitnum) - 684usize];
    ["Offset of field: model_t::PTmode"][::std::mem::offset_of!(model_t, PTmode) - 688usize];
    ["Offset of field: model_t::za_unitnum"]
        [::std::mem::offset_of!(model_t, za_unitnum) - 692usize];
    ["Offset of field: model_t::log_runtimes"]
        [::std::mem::offset_of!(model_t, log_runtimes) - 696usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct layer_t {
    pub P: f64,
    pub T: f64,
    pub dP: f64,
    pub dP_def: f64,
    pub dphi: f64,
    pub Pbase: f64,
    pub Tbase: f64,
    pub h: f64,
    pub m: f64,
    pub Mair: f64,
    pub M0: f64,
    pub gbase: f64,
    pub nbase: f64,
    pub zbase: f64,
    pub za_base: f64,
    pub B: *mut f64,
    pub tau: *mut f64,
    pub tx: *mut f64,
    pub column: *mut *mut column_t,
    pub lineshape: *mut ::std::os::raw::c_int,
    pub strict_selfbroad: *mut ::std::os::raw::c_int,
    pub Mair_flag: *mut ::std::os::raw::c_int,
    pub runtime: f64,
    pub tagnum: ::std::os::raw::c_int,
    pub type_: ::std::os::raw::c_int,
    pub ncols: ::std::os::raw::c_int,
    pub P_unitnum: ::std::os::raw::c_int,
    pub T_unitnum: ::std::os::raw::c_int,
    pub h_unitnum: ::std::os::raw::c_int,
    pub updateflag: ::std::os::raw::c_int,
    pub vmr_stat: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of layer_t"][::std::mem::size_of::<layer_t>() - 216usize];
    ["Alignment of layer_t"][::std::mem::align_of::<layer_t>() - 8usize];
    ["Offset of field: layer_t::P"][::std::mem::offset_of!(layer_t, P) - 0usize];
    ["Offset of field: layer_t::T"][::std::mem::offset_of!(layer_t, T) - 8usize];
    ["Offset of field: layer_t::dP"][::std::mem::offset_of!(layer_t, dP) - 16usize];
    ["Offset of field: layer_t::dP_def"][::std::mem::offset_of!(layer_t, dP_def) - 24usize];
    ["Offset of field: layer_t::dphi"][::std::mem::offset_of!(layer_t, dphi) - 32usize];
    ["Offset of field: layer_t::Pbase"][::std::mem::offset_of!(layer_t, Pbase) - 40usize];
    ["Offset of field: layer_t::Tbase"][::std::mem::offset_of!(layer_t, Tbase) - 48usize];
    ["Offset of field: layer_t::h"][::std::mem::offset_of!(layer_t, h) - 56usize];
    ["Offset of field: layer_t::m"][::std::mem::offset_of!(layer_t, m) - 64usize];
    ["Offset of field: layer_t::Mair"][::std::mem::offset_of!(layer_t, Mair) - 72usize];
    ["Offset of field: layer_t::M0"][::std::mem::offset_of!(layer_t, M0) - 80usize];
    ["Offset of field: layer_t::gbase"][::std::mem::offset_of!(layer_t, gbase) - 88usize];
    ["Offset of field: layer_t::nbase"][::std::mem::offset_of!(layer_t, nbase) - 96usize];
    ["Offset of field: layer_t::zbase"][::std::mem::offset_of!(layer_t, zbase) - 104usize];
    ["Offset of field: layer_t::za_base"][::std::mem::offset_of!(layer_t, za_base) - 112usize];
    ["Offset of field: layer_t::B"][::std::mem::offset_of!(layer_t, B) - 120usize];
    ["Offset of field: layer_t::tau"][::std::mem::offset_of!(layer_t, tau) - 128usize];
    ["Offset of field: layer_t::tx"][::std::mem::offset_of!(layer_t, tx) - 136usize];
    ["Offset of field: layer_t::column"][::std::mem::offset_of!(layer_t, column) - 144usize];
    ["Offset of field: layer_t::lineshape"][::std::mem::offset_of!(layer_t, lineshape) - 152usize];
    ["Offset of field: layer_t::strict_selfbroad"]
        [::std::mem::offset_of!(layer_t, strict_selfbroad) - 160usize];
    ["Offset of field: layer_t::Mair_flag"][::std::mem::offset_of!(layer_t, Mair_flag) - 168usize];
    ["Offset of field: layer_t::runtime"][::std::mem::offset_of!(layer_t, runtime) - 176usize];
    ["Offset of field: layer_t::tagnum"][::std::mem::offset_of!(layer_t, tagnum) - 184usize];
    ["Offset of field: layer_t::type_"][::std::mem::offset_of!(layer_t, type_) - 188usize];
    ["Offset of field: layer_t::ncols"][::std::mem::offset_of!(layer_t, ncols) - 192usize];
    ["Offset of field: layer_t::P_unitnum"][::std::mem::offset_of!(layer_t, P_unitnum) - 196usize];
    ["Offset of field: layer_t::T_unitnum"][::std::mem::offset_of!(layer_t, T_unitnum) - 200usize];
    ["Offset of field: layer_t::h_unitnum"][::std::mem::offset_of!(layer_t, h_unitnum) - 204usize];
    ["Offset of field: layer_t::updateflag"]
        [::std::mem::offset_of!(layer_t, updateflag) - 208usize];
    ["Offset of field: layer_t::vmr_stat"][::std::mem::offset_of!(layer_t, vmr_stat) - 212usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct column_t {
    pub N: f64,
    pub N_def: f64,
    pub N_scaled: f64,
    pub xvmr: f64,
    pub vmr_scaled: f64,
    pub RH: f64,
    pub RH_adj: f64,
    pub ztau: *mut f64,
    pub abscoeff: *mut *mut abscoeff_t,
    pub runtime: f64,
    pub col_typenum: ::std::os::raw::c_int,
    pub n_abscoeffs: ::std::os::raw::c_int,
    pub N_mode: ::std::os::raw::c_int,
    pub N_unitnum: ::std::os::raw::c_int,
    pub vmr_stat: ::std::os::raw::c_int,
    pub unres_lines: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of column_t"][::std::mem::size_of::<column_t>() - 104usize];
    ["Alignment of column_t"][::std::mem::align_of::<column_t>() - 8usize];
    ["Offset of field: column_t::N"][::std::mem::offset_of!(column_t, N) - 0usize];
    ["Offset of field: column_t::N_def"][::std::mem::offset_of!(column_t, N_def) - 8usize];
    ["Offset of field: column_t::N_scaled"][::std::mem::offset_of!(column_t, N_scaled) - 16usize];
    ["Offset of field: column_t::xvmr"][::std::mem::offset_of!(column_t, xvmr) - 24usize];
    ["Offset of field: column_t::vmr_scaled"]
        [::std::mem::offset_of!(column_t, vmr_scaled) - 32usize];
    ["Offset of field: column_t::RH"][::std::mem::offset_of!(column_t, RH) - 40usize];
    ["Offset of field: column_t::RH_adj"][::std::mem::offset_of!(column_t, RH_adj) - 48usize];
    ["Offset of field: column_t::ztau"][::std::mem::offset_of!(column_t, ztau) - 56usize];
    ["Offset of field: column_t::abscoeff"][::std::mem::offset_of!(column_t, abscoeff) - 64usize];
    ["Offset of field: column_t::runtime"][::std::mem::offset_of!(column_t, runtime) - 72usize];
    ["Offset of field: column_t::col_typenum"]
        [::std::mem::offset_of!(column_t, col_typenum) - 80usize];
    ["Offset of field: column_t::n_abscoeffs"]
        [::std::mem::offset_of!(column_t, n_abscoeffs) - 84usize];
    ["Offset of field: column_t::N_mode"][::std::mem::offset_of!(column_t, N_mode) - 88usize];
    ["Offset of field: column_t::N_unitnum"][::std::mem::offset_of!(column_t, N_unitnum) - 92usize];
    ["Offset of field: column_t::vmr_stat"][::std::mem::offset_of!(column_t, vmr_stat) - 96usize];
    ["Offset of field: column_t::unres_lines"]
        [::std::mem::offset_of!(column_t, unres_lines) - 100usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct abscoeff_t {
    pub vmr_selfbroad: f64,
    pub k: *mut f64,
    pub kcache: *mut *mut f64,
    pub k_typenum: ::std::os::raw::c_int,
    pub unres_lines: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of abscoeff_t"][::std::mem::size_of::<abscoeff_t>() - 32usize];
    ["Alignment of abscoeff_t"][::std::mem::align_of::<abscoeff_t>() - 8usize];
    ["Offset of field: abscoeff_t::vmr_selfbroad"]
        [::std::mem::offset_of!(abscoeff_t, vmr_selfbroad) - 0usize];
    ["Offset of field: abscoeff_t::k"][::std::mem::offset_of!(abscoeff_t, k) - 8usize];
    ["Offset of field: abscoeff_t::kcache"][::std::mem::offset_of!(abscoeff_t, kcache) - 16usize];
    ["Offset of field: abscoeff_t::k_typenum"]
        [::std::mem::offset_of!(abscoeff_t, k_typenum) - 24usize];
    ["Offset of field: abscoeff_t::unres_lines"]
        [::std::mem::offset_of!(abscoeff_t, unres_lines) - 28usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct simplex_t {
    pub E1: f64,
    pub E2: f64,
    pub tol: f64,
    pub name: *mut *mut ::std::os::raw::c_char,
    pub init: *mut f64,
    pub scale: *mut f64,
    pub unitnum: *mut ::std::os::raw::c_int,
    pub mapping: *mut ::std::os::raw::c_int,
    pub varptr: *mut *mut f64,
    pub vertex: *mut *mut f64,
    pub E: *mut f64,
    pub pbar: *mut f64,
    pub p1: *mut f64,
    pub p2: *mut f64,
    pub pc: *mut f64,
    pub ihigh: ::std::os::raw::c_uint,
    pub ilow: ::std::os::raw::c_uint,
    pub n: ::std::os::raw::c_uint,
    pub iter: ::std::os::raw::c_int,
    pub reinit: ::std::os::raw::c_int,
    pub restart_count: ::std::os::raw::c_int,
    pub logarithmic: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of simplex_t"][::std::mem::size_of::<simplex_t>() - 152usize];
    ["Alignment of simplex_t"][::std::mem::align_of::<simplex_t>() - 8usize];
    ["Offset of field: simplex_t::E1"][::std::mem::offset_of!(simplex_t, E1) - 0usize];
    ["Offset of field: simplex_t::E2"][::std::mem::offset_of!(simplex_t, E2) - 8usize];
    ["Offset of field: simplex_t::tol"][::std::mem::offset_of!(simplex_t, tol) - 16usize];
    ["Offset of field: simplex_t::name"][::std::mem::offset_of!(simplex_t, name) - 24usize];
    ["Offset of field: simplex_t::init"][::std::mem::offset_of!(simplex_t, init) - 32usize];
    ["Offset of field: simplex_t::scale"][::std::mem::offset_of!(simplex_t, scale) - 40usize];
    ["Offset of field: simplex_t::unitnum"][::std::mem::offset_of!(simplex_t, unitnum) - 48usize];
    ["Offset of field: simplex_t::mapping"][::std::mem::offset_of!(simplex_t, mapping) - 56usize];
    ["Offset of field: simplex_t::varptr"][::std::mem::offset_of!(simplex_t, varptr) - 64usize];
    ["Offset of field: simplex_t::vertex"][::std::mem::offset_of!(simplex_t, vertex) - 72usize];
    ["Offset of field: simplex_t::E"][::std::mem::offset_of!(simplex_t, E) - 80usize];
    ["Offset of field: simplex_t::pbar"][::std::mem::offset_of!(simplex_t, pbar) - 88usize];
    ["Offset of field: simplex_t::p1"][::std::mem::offset_of!(simplex_t, p1) - 96usize];
    ["Offset of field: simplex_t::p2"][::std::mem::offset_of!(simplex_t, p2) - 104usize];
    ["Offset of field: simplex_t::pc"][::std::mem::offset_of!(simplex_t, pc) - 112usize];
    ["Offset of field: simplex_t::ihigh"][::std::mem::offset_of!(simplex_t, ihigh) - 120usize];
    ["Offset of field: simplex_t::ilow"][::std::mem::offset_of!(simplex_t, ilow) - 124usize];
    ["Offset of field: simplex_t::n"][::std::mem::offset_of!(simplex_t, n) - 128usize];
    ["Offset of field: simplex_t::iter"][::std::mem::offset_of!(simplex_t, iter) - 132usize];
    ["Offset of field: simplex_t::reinit"][::std::mem::offset_of!(simplex_t, reinit) - 136usize];
    ["Offset of field: simplex_t::restart_count"]
        [::std::mem::offset_of!(simplex_t, restart_count) - 140usize];
    ["Offset of field: simplex_t::logarithmic"]
        [::std::mem::offset_of!(simplex_t, logarithmic) - 144usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fit_data_t {
    pub filename: *mut *mut ::std::os::raw::c_char,
    pub fp: *mut FILE,
    pub f: *mut f64,
    pub s: *mut f64,
    pub s_mod: *mut f64,
    pub res: *mut f64,
    pub res_est: *mut f64,
    pub b: *mut f64,
    pub w: *mut f64,
    pub mean_var: f64,
    pub mean_var_tracked: f64,
    pub res_track_gain: f64,
    pub runtime: f64,
    pub npts: gridsize_t,
    pub nalloc: gridsize_t,
    pub data_type: ::std::os::raw::c_int,
    pub estimator_type: ::std::os::raw::c_int,
    pub f_unitnum: ::std::os::raw::c_int,
    pub s_unitnum: ::std::os::raw::c_int,
    pub f_col: ::std::os::raw::c_int,
    pub s_col: ::std::os::raw::c_int,
    pub b_col: ::std::os::raw::c_int,
    pub w_col: ::std::os::raw::c_int,
    pub max_iter: ::std::os::raw::c_int,
    pub max_restarts: ::std::os::raw::c_int,
    pub nfiles: ::std::os::raw::c_int,
    pub open_filenum: ::std::os::raw::c_int,
    pub blocknum: ::std::os::raw::c_int,
    pub output_mode: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of fit_data_t"][::std::mem::size_of::<fit_data_t>() - 168usize];
    ["Alignment of fit_data_t"][::std::mem::align_of::<fit_data_t>() - 8usize];
    ["Offset of field: fit_data_t::filename"]
        [::std::mem::offset_of!(fit_data_t, filename) - 0usize];
    ["Offset of field: fit_data_t::fp"][::std::mem::offset_of!(fit_data_t, fp) - 8usize];
    ["Offset of field: fit_data_t::f"][::std::mem::offset_of!(fit_data_t, f) - 16usize];
    ["Offset of field: fit_data_t::s"][::std::mem::offset_of!(fit_data_t, s) - 24usize];
    ["Offset of field: fit_data_t::s_mod"][::std::mem::offset_of!(fit_data_t, s_mod) - 32usize];
    ["Offset of field: fit_data_t::res"][::std::mem::offset_of!(fit_data_t, res) - 40usize];
    ["Offset of field: fit_data_t::res_est"][::std::mem::offset_of!(fit_data_t, res_est) - 48usize];
    ["Offset of field: fit_data_t::b"][::std::mem::offset_of!(fit_data_t, b) - 56usize];
    ["Offset of field: fit_data_t::w"][::std::mem::offset_of!(fit_data_t, w) - 64usize];
    ["Offset of field: fit_data_t::mean_var"]
        [::std::mem::offset_of!(fit_data_t, mean_var) - 72usize];
    ["Offset of field: fit_data_t::mean_var_tracked"]
        [::std::mem::offset_of!(fit_data_t, mean_var_tracked) - 80usize];
    ["Offset of field: fit_data_t::res_track_gain"]
        [::std::mem::offset_of!(fit_data_t, res_track_gain) - 88usize];
    ["Offset of field: fit_data_t::runtime"][::std::mem::offset_of!(fit_data_t, runtime) - 96usize];
    ["Offset of field: fit_data_t::npts"][::std::mem::offset_of!(fit_data_t, npts) - 104usize];
    ["Offset of field: fit_data_t::nalloc"][::std::mem::offset_of!(fit_data_t, nalloc) - 108usize];
    ["Offset of field: fit_data_t::data_type"]
        [::std::mem::offset_of!(fit_data_t, data_type) - 112usize];
    ["Offset of field: fit_data_t::estimator_type"]
        [::std::mem::offset_of!(fit_data_t, estimator_type) - 116usize];
    ["Offset of field: fit_data_t::f_unitnum"]
        [::std::mem::offset_of!(fit_data_t, f_unitnum) - 120usize];
    ["Offset of field: fit_data_t::s_unitnum"]
        [::std::mem::offset_of!(fit_data_t, s_unitnum) - 124usize];
    ["Offset of field: fit_data_t::f_col"][::std::mem::offset_of!(fit_data_t, f_col) - 128usize];
    ["Offset of field: fit_data_t::s_col"][::std::mem::offset_of!(fit_data_t, s_col) - 132usize];
    ["Offset of field: fit_data_t::b_col"][::std::mem::offset_of!(fit_data_t, b_col) - 136usize];
    ["Offset of field: fit_data_t::w_col"][::std::mem::offset_of!(fit_data_t, w_col) - 140usize];
    ["Offset of field: fit_data_t::max_iter"]
        [::std::mem::offset_of!(fit_data_t, max_iter) - 144usize];
    ["Offset of field: fit_data_t::max_restarts"]
        [::std::mem::offset_of!(fit_data_t, max_restarts) - 148usize];
    ["Offset of field: fit_data_t::nfiles"][::std::mem::offset_of!(fit_data_t, nfiles) - 152usize];
    ["Offset of field: fit_data_t::open_filenum"]
        [::std::mem::offset_of!(fit_data_t, open_filenum) - 156usize];
    ["Offset of field: fit_data_t::blocknum"]
        [::std::mem::offset_of!(fit_data_t, blocknum) - 160usize];
    ["Offset of field: fit_data_t::output_mode"]
        [::std::mem::offset_of!(fit_data_t, output_mode) - 164usize];
};
unsafe extern "C" {
    pub fn compute_model(arg1: *mut model_t, arg2: *mut model_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn setup_atmospheric_model(arg1: *mut model_t, arg2: *mut model_t)
    -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn total_airmass(arg1: *mut model_t) -> f64;
}
unsafe extern "C" {
    pub fn total_refraction(arg1: *mut model_t) -> f64;
}
unsafe extern "C" {
    pub fn parse_config_file(
        arg1: ::std::os::raw::c_int,
        arg2: *mut *mut ::std::os::raw::c_char,
        arg3: *mut model_t,
        arg4: *mut fit_data_t,
        arg5: *mut simplex_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn free_fit_data_entities(arg1: *mut fit_data_t);
}
unsafe extern "C" {
    pub fn free_model_entities(arg1: *mut model_t);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct output_tabentry {
    pub name: *const ::std::os::raw::c_char,
    pub spectrum: *mut f64,
    pub jacobian: *mut *mut f64,
    pub jacobian_round_err: *mut *mut f64,
    pub jacobian_trunc_err: *mut *mut f64,
    pub jacobian_sorted_err: *mut *mut f64,
    pub default_unitnum: ::std::os::raw::c_int,
    pub unitnum: ::std::os::raw::c_int,
    pub k_typenum: ::std::os::raw::c_int,
    pub flags: ::std::os::raw::c_int,
    pub format: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of output_tabentry"][::std::mem::size_of::<output_tabentry>() - 72usize];
    ["Alignment of output_tabentry"][::std::mem::align_of::<output_tabentry>() - 8usize];
    ["Offset of field: output_tabentry::name"]
        [::std::mem::offset_of!(output_tabentry, name) - 0usize];
    ["Offset of field: output_tabentry::spectrum"]
        [::std::mem::offset_of!(output_tabentry, spectrum) - 8usize];
    ["Offset of field: output_tabentry::jacobian"]
        [::std::mem::offset_of!(output_tabentry, jacobian) - 16usize];
    ["Offset of field: output_tabentry::jacobian_round_err"]
        [::std::mem::offset_of!(output_tabentry, jacobian_round_err) - 24usize];
    ["Offset of field: output_tabentry::jacobian_trunc_err"]
        [::std::mem::offset_of!(output_tabentry, jacobian_trunc_err) - 32usize];
    ["Offset of field: output_tabentry::jacobian_sorted_err"]
        [::std::mem::offset_of!(output_tabentry, jacobian_sorted_err) - 40usize];
    ["Offset of field: output_tabentry::default_unitnum"]
        [::std::mem::offset_of!(output_tabentry, default_unitnum) - 48usize];
    ["Offset of field: output_tabentry::unitnum"]
        [::std::mem::offset_of!(output_tabentry, unitnum) - 52usize];
    ["Offset of field: output_tabentry::k_typenum"]
        [::std::mem::offset_of!(output_tabentry, k_typenum) - 56usize];
    ["Offset of field: output_tabentry::flags"]
        [::std::mem::offset_of!(output_tabentry, flags) - 60usize];
    ["Offset of field: output_tabentry::format"]
        [::std::mem::offset_of!(output_tabentry, format) - 64usize];
};
unsafe extern "C" {
    pub static mut output: [output_tabentry; 14usize]; // OUTPUT_END_OF_TABLE + 1
}
pub const OUTPUT_NONE: _bindgen_ty_6 = 0;
pub const OUTPUT_FREQUENCY: _bindgen_ty_6 = 1;
pub const OUTPUT_OPACITY: _bindgen_ty_6 = 2;
pub const OUTPUT_TRANSMITTANCE: _bindgen_ty_6 = 3;
pub const OUTPUT_RADIANCE: _bindgen_ty_6 = 4;
pub const OUTPUT_RADIANCE_DIFF: _bindgen_ty_6 = 5;
pub const OUTPUT_TB_PLANCK: _bindgen_ty_6 = 6;
pub const OUTPUT_TB_RAYLEIGH_JEANS: _bindgen_ty_6 = 7;
pub const OUTPUT_TSYS: _bindgen_ty_6 = 8;
pub const OUTPUT_Y: _bindgen_ty_6 = 9;
pub const OUTPUT_DELAY: _bindgen_ty_6 = 10;
pub const OUTPUT_FREE_SPACE_LOSS: _bindgen_ty_6 = 11;
pub const OUTPUT_K: _bindgen_ty_6 = 12;
pub const OUTPUT_END_OF_TABLE: _bindgen_ty_6 = 13;
pub type _bindgen_ty_6 = ::std::os::raw::c_uint;
pub const ALL_OUTPUTS: _bindgen_ty_7 = 13;
pub type _bindgen_ty_7 = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub static mut outcol: [::std::os::raw::c_int; 13usize]; // OUTPUT_END_OF_TABLE
}
unsafe extern "C" {
    pub fn set_active_outputs(arg1: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn errstat() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn print_errlog() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn kcache_free_all();
}
unsafe extern "C" {
    pub fn free_Nscale_list();
}
unsafe extern "C" {
    pub fn free_tag_string_table() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn free_simplex_entities(arg1: *mut simplex_t);
}
