name: Lint/format and test

on:
  push:
    branches:
      - "**"
    paths:
      - "**/*.rs"
      - "**/*.py"
      - "**/*.pyi"
      - "Cargo.toml"
      - "Cargo.lock"
      - "build.rs"
      - "pyproject.toml"
      - "uv.lock"
      - "justfile"
      - ".pre-commit-config.yaml"
      - ".github/actions/setup-am/**"
      - ".github/workflows/*.yaml"
      - ".github/workflows/*.yml"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-lint-format:
    name: Rust lint and format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup am source
        uses: ./.github/actions/setup-am

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy

      - name: Install just
        uses: extractions/setup-just@v4

      - name: Check Rust formatting
        run: just fmt-check rs

      - name: Run Rust lints
        run: just lint rs

  python-lint-format:
    name: Python lint and format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install just
        uses: extractions/setup-just@v4

      - name: Check Python formatting
        run: just fmt-check py

      - name: Run Python lints
        run: just lint py

  rust-tests:
    name: Rust tests
    needs: rust-lint-format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup am source and fixture
        uses: ./.github/actions/setup-am
        with:
          download-amc: "true"

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install just
        uses: extractions/setup-just@v4

      - name: Run Rust tests
        run: just test rs

  python-tests:
    name: Python tests
    needs: python-lint-format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.14"

    steps:
      - uses: actions/checkout@v6

      - name: Setup am source and fixture
        uses: ./.github/actions/setup-am
        with:
          download-amc: "true"

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install just
        uses: extractions/setup-just@v4

      - name: Run Python tests
        run: just test py
